server:
  port: "9090"
spring:

  profiles:
    active: "prod"

  main:
    banner-mode: "off"
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
        format_sql: "true"
  servlet:
    multipart:
      max-file-size: "5MB"
      max-request-size: "5MB"
api:
  prefix: "/api/v1"
auth:
  token:
    expirationInMils: "3600000"
    jwtSecret: "122333444455555666666777777788888888999999999"
